mybatis:
  mapper-locations: mapper/*.xml

spring:
  datasource:
    "driver-class-name": com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: root
    password: dbcjs4
  mvc:
    view:
      prefix: /views/
      suffix: .html

logging:
  level:
    org:
      springframework: INFO